/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.6/userguide/building_java_projects.html
 * This project uses @Incubating APIs which are subject to change.
 */
plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.7.10"
    id("com.github.johnrengelman.shadow") version "7.1.2"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
  implementation("com.google.guava:guava:31.1-jre")
  implementation("com.amazonaws:aws-lambda-java-core:1.2.2")
  implementation("com.amazonaws:aws-lambda-java-events:3.11.0")
  implementation("com.amazonaws:aws-java-sdk-dynamodb:1.12.372")
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use Kotlin Test framework
            useKotlinTest("1.7.10")

            dependencies {
                // Use newer version of JUnit Engine for Kotlin Test
                implementation("org.junit.jupiter:junit-jupiter-engine:5.9.1")
            }
        }
    }
}

java {
  targetCompatibility = JavaVersion.VERSION_11
}

tasks.register<Zip>("makeDeploymentBundle") {
  archiveBaseName.set("lambda-deployment-bundle")
  destinationDirectory.set(project.layout.buildDirectory.dir("archives"))
  from(project.zipTree("$buildDir/libs/app-all.jar"))
  from(file("$projectDir")) {
    include("build.gradle.kts")
  }
  duplicatesStrategy = DuplicatesStrategy.FAIL

  dependsOn("shadowJar")
}

